<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ATMECSINLT-004" failures="1" tests="4" name="com.automationpractice.testscripts.TC01_Login_Logout" time="44.802" errors="0" timestamp="2021-10-14T19:03:43 IST" skipped="2">
  <testcase classname="com.automationpractice.testscripts.TC01_Login_Logout" name="login_Logout_Validation" time="20.237"/>
  <system-out>
    <![CDATA[Clicked on Header Login Button
Field Login user name is filled with testnew1
Field Login password is filled with test@123
Clicked on Login Button
Login Successful
Clicked on Logout Button
Logout Successful]]>
  </system-out>
  <testcase classname="com.automationpractice.testscripts.TC01_Login_Logout" name="validate_Header_Links" time="9.211">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.automationpractice.testscripts.TC01_Login_Logout.validate_Header_Links(TC01_Login_Logout.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validate_Header_Links -->
  <system-out>
    <![CDATA[Capturing screenshot: Thu_Oct_14_19_03_40_IST_2021.jpg]]>
  </system-out>
  <testcase classname="com.automationpractice.testscripts.TC01_Login_Logout" name="validate_Header_Links" time="7.688">
    <skipped/>
  </testcase> <!-- validate_Header_Links -->
  <system-out/>
  <testcase classname="com.automationpractice.testscripts.TC01_Login_Logout" name="validate_Header_Links" time="7.666">
    <skipped/>
  </testcase> <!-- validate_Header_Links -->
  <system-out/>
</testsuite> <!-- com.automationpractice.testscripts.TC01_Login_Logout -->
